#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  write_date=""
  in_file=""
  out_file=""
  out_dir=""
  work_dir=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'cacaview' \
    'libcaca'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_out_file_auto_detect() {
  echo \
    "$(_get \
         "in" \
         "file").txt"
}

_hardhat_init() {
  local \
    _oldpwd
  _oldpwd="$( \
    pwd)"
  cd \
    "${_project_dir}"
  echo \
    "3\n" | \
    npx \
      hardhat \
        init
  rm \
    -rf \
    "contracts/Lock.sol"
  cd \
    "${_oldpwd}"
}

_close_keyboard() {
  sdotool \
    key \
      back
}

_caca_view_quit() {
  sleep \
    4
  sdotool \
    key \
      q
}

_android_caca_write() {
  _close_keyboard
  cacaview \
    "${_in}" > \
    "${_out}" & \
  _caca_view_quit 
}

_caca_view() {
  local \
    _in_file="${1}" \
    _out_file="${2}" \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    "_${_os}_caca_write"
  fi
}

_out_dir_auto_detect(){
  local \
    _contract_dir
  if [[ "$(_get "target" "contracts")" != "" ]]; then
    _contract_dir="$( \
      dirname \
       "${target_contracts}")"
  else
    _contract_dir="$( \
      pwd)"
  fi
  echo \
    "${_contract_dir}"
}

_set_overrides() {
  _set_override \
    "build" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "compiler" \
    "backend" \
    "hardhat"
  _set_override \
    "work" \
    "dir" \
    "$(mktemp \
         -d)"
  _set_override \
    "out" \
    "dir" \
    "$(_out_dir_auto_detect)"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Solidity compiler.

Usage:
  $(_get "app" "name")
    [options]
    [target_contract]
  options:
     -b <backend>         Compiler backend
                          Default: '$(_get "compiler" "backend")'
     -o <out_dir>         Output directory
                          Default: '$(_get "out" "dir")'
     -w <work_dir>        Work directory
                          Default: '$(_get "work" "dir")'

     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "               Build date:   $(_get "build" "date")"
  _msg_info "         Compiler backend:   $(_get "compiler" "backend")"
  _msg_info "                  Out dir:   $(_get "out" "dir")"
  _msg_info "                 Work dir:   $(_get "work" "dir")"
  _msg_info "         Target contracts:   $(_get "target" "contracts")"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'b:o:w:cvh?' \
    arg; do
  case \
    "${arg}" in
    b) override_compiler_backend="${OPTARG}" ;;
    o) override_out_dir="${OPTARG}" ;;
    w) override_work_dir="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( 0 < $# )); then
  _set \
    "in" \
    "file" \
    "${1}"
fi
if (( 1 < $# )); then
  _set \
    "out" \
    "file" \
    "${2}"
fi
if [[ "${in_file}" ==  "" ]]; then
  _msg_error \
    "no input file" \
    0
  _set_overrides
  _usage \
    1
fi
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$(_get \
       "in" \
       "file")"
  "$(_get \
       "out" \
       "file")"
)
_caca_write \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
