#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"

# shellcheck disable=SC2034
_global_variables() {
  write_date=""
  in_file=""
  out_file=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'cacaview' \
    'libcaca'
  _check_cmd \
    'sdotool'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/${app_name}"
  echo \
    "${_dir}"
}

_close_keyboard() {
  sdotool \
    key \
      back
}

_caca_view_quit() {
  sleep \
    10
  sdotool \
    key \
      q
}

_encode() {
  local \
    _in="${1}" \
    _pic
  _msg_info \
    "in file: ${_in}"
  _pic="$( \
    cat \
      "${_in}" | \
      sed \
        "s/cacaview//g")" || \
    true
  _msg_info \
    "pic size: ${#_pic}"
  _msg_info \
    "out file: ${_out}"
  if [ ! -e "${_out}" ] && \
     [[ "${_os}" == "Android" ]]; then
    touch \
      "${_out}" || \
    true
  fi
  echo \
    "${_pic:30}" > \
    "${_out}"
}

_android_cacawrite() {
  local \
    _in="${1}" \
    _out="${2}" \
    _tmp
  _tmp="$( \
    mktemp \
      --suffix=".txt")"
  _close_keyboard
  _caca_view_quit & \
  cacaview \
    "${_in}" > \
    "${_tmp}"
  _msg_info \
    "out file '${_out}', tmp file ${_tmp}"
  _encode \
    "${_tmp}"
}

_linux_cacawrite() {
  local \
    _in="${1}" \
    _out="${2}" \
    _tmp
  _tmp="$( \
    mktemp \
      --suffix=".txt")"
  timeout \
    5 \
    cacaview \
      "${_in}" 2>/dev/null 1&> \
    "${_tmp}" || 
    true
  _encode \
    "${_tmp}"
}

_cacawrite() {
  local \
    _in="${1}" \
    _out="${2}" \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    "_android_cacawrite" \
      "${_in}" \
      "${_out}"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    "_linux_cacawrite" \
      "${_in}" \
      "${_out}"
  fi
}

_out_file_auto_detect(){
  local \
    _out='' \
    _in
  _in="$( \
    _get \
      "in" \
      "file")"
  if [[ "${_in}" != "" ]]; then
    _out="${_in}.txt"
  fi
  echo \
    "${_out}"
}

_set_overrides() {
  _set_override \
    "write" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "out" \
    "file" \
    "$(_out_file_auto_detect)"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Converts an image into text.

Usage:
  ${app_name}
    [options]
    <in_file>
    (<out_file>)

  options:
     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "               Write date:   ${write_date}"
  _msg_info "                  In file:   ${in_file}"
  _msg_info "                 Out file:   ${out_file}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( 0 == $# )); then
  _msg_error \
    "no input file" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  _set \
    "in" \
    "file" \
    "$(realpath \
         "${1}")"
fi
if (( 1 < $# )); then
  _set \
    "out" \
    "file" \
    "${2}"
fi
_set_overrides
_config_user_init \
  "${app_name}"
_show_config
app_opts=(
  "${in_file}"
  "${out_file}"
)
_cacawrite \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
